# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_field', to=settings.AUTH_USER_MODEL),
        ),
    ]
