# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_pin_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='description',
        ),
    ]
