# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-06 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0004_auto_20180806_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pin',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
